package com.scholartrack.model;

public enum AuditAction {
    USER_REGISTER,
    USER_LOGIN,
    APPLICATION_SUBMITTED,
    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFIED,
    DOCUMENT_FLAGGED,
    ELIGIBILITY_EVALUATED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    DISBURSEMENT_INITIATED,
    SCHOLARSHIP_CREATED,
    SCHOLARSHIP_UPDATED
}
